2019-02-12 16:39:31,627 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:40:47,405 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:42:11,916 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:44:53,582 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:45:30,610 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:49:20,257 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:49:47,800 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:50:54,742 - tools.log - ERROR - 任务开始！！！
2019-02-12 16:53:22,747 - tools.log - ERROR - 任务开始！！！
2019-02-12 17:00:03,107 - tools.log - ERROR - 任务开始！！！
2019-02-12 17:01:33,288 - tools.log - ERROR - 任务开始！！！
2019-03-21 16:40:55,530 - tools.log - ERROR - invalid literal for int() with base 10: '["1"]'
2019-03-21 16:41:27,373 - tools.log - ERROR - invalid literal for int() with base 10: '["1"]'
2019-03-21 16:43:57,925 - tools.log - ERROR - invalid literal for int() with base 10: '['
2019-03-21 16:44:00,918 - tools.log - ERROR - invalid literal for int() with base 10: '['
2019-03-21 16:45:26,917 - tools.log - ERROR - invalid literal for int() with base 10: '['
2019-03-21 16:46:47,511 - tools.log - ERROR - 'int' object is not iterable
2019-03-21 16:48:13,198 - tools.log - ERROR - invalid literal for int() with base 10: '['
2019-03-21 17:01:41,008 - tools.log - ERROR - module 'django.core.serializers.json' has no attribute 'loads'
2019-03-21 17:12:31,212 - tools.log - ERROR - the JSON object must be str, bytes or bytearray, not 'NoneType'
2019-03-21 17:22:26,309 - tools.log - ERROR - the JSON object must be str, bytes or bytearray, not 'NoneType'
2019-04-29 20:26:20,604 - django.request - ERROR - Internal Server Error: /get_case_apis/
Traceback (most recent call last):
  File "D:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Program Files\python\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Program Files\IAM\api\views.py", line 760, in get_case_apis
    de['case_api_update_time'] = ca.case_update_time.strftime("%Y-%m-%d %H:%M:%S")
AttributeError: 'CaseApi' object has no attribute 'case_update_time'
